src/accounts/urls.py
from django.urls import path, re_path

from django.contrib.auth import views as auth_views
from .views import UserCreateView, UserUpdateView, activate, UserDetailView, thanks
from .views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView, LoginView, LogoutView

from django.urls import reverse_lazy

app_name = 'accounts'


urlpatterns = [

    path('register/', UserCreateView.as_view(), name='register'),
    path('thanks/', thanks, name='thanks'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    path('edit/', UserUpdateView.as_view(), name="edit"),
    path('', UserDetailView.as_view(), name="profile" ),

    re_path(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', PasswordResetCompleteView.as_view(), name='password_reset_complete', ),
    re_path(r'^password_change/$', PasswordChangeView.as_view(), name="password_change"),
    re_path(r'^password_change/done/$', PasswordChangeDoneView.as_view(), name="password_change_done"),

]

src/tasks/urls.py
from django.urls import path, re_path
from .views import CourseList, CourseCreate, CourseDetail, CourseUpdate, GlobalCourseList
from .views import TaskList, TaskCreate, TaskDetail, TaskUpdate
from .views import Subscribe, Unsubscribe, ToggleLike
from .views import TableCreate, DatabaseCreate
from .views import TestMysql, DatabaseDetail, TableDetail, UpdateProgress

from einvite.views import invites

app_name = 'tasks'


urlpatterns = [

    path('all/', GlobalCourseList.as_view(), name='global_course_list'),

    path('', CourseList.as_view(), name='course_list'),
    path('new/', CourseCreate.as_view(), name='create_course'),
    path('<int:pk>/', CourseDetail.as_view(), name='view_course'),
    path('<int:pk>/like', ToggleLike.as_view(), name='like_course'),
    path('<int:pk>/edit/', CourseUpdate.as_view(), name='update_course'),

    path('<int:course_id>/tasks/', TaskList.as_view(), name='task_list'),
    path('<int:course_id>/tasks/new/', TaskCreate.as_view(), name='create_task'),
    path('<int:course_id>/tasks/<int:pk>/', TaskDetail.as_view(), name='view_task'),
    path('<int:course_id>/tasks/<int:pk>/progress', UpdateProgress.as_view(), name='update_progress'),
    path('<int:course_id>/tasks/<int:pk>/edit/', TaskUpdate.as_view(), name='update_task'),

    path('<int:course_id>/invite/', invites, name='invite_students'),

    path('<int:pk>/subscribe/', Subscribe.as_view(), name="course_subscribe"),
    path('<int:pk>/unsubscribe/', Unsubscribe.as_view(), name="course_unsubscribe"),

    path('db/new/', DatabaseCreate.as_view(), name="create_db"),
    path('db/<int:pk>', DatabaseDetail.as_view(), name="view_task_db"),
    path('table/new/', TableCreate.as_view(), name="create_table"),
    path('table/<int:pk>', TableDetail.as_view(), name="view_task_table"),

    path('test/', TestMysql.as_view()),



]

src/tasks/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.utils import timezone
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.db.models import F, Count, Value

from .forms import CourseForm, TaskForm, DataBaseForm, TableForm
from .models import Course, Task, Progress, Subscribes, Task_db, Task_table

from django.shortcuts import redirect, get_object_or_404


from dbmanager.manager import DBManager


class CourseCreate(CreateView):
    template_name = 'tasks/course_form.html'
    form_class = CourseForm
    model = Course

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_teacher:
            return redirect('tasks:course_list')
        return super(CourseCreate, self).dispatch(request, *args, **kwargs)


    def form_valid(self, form):
        form.instance.owner = self.request.user
        if 'is_published' in form.cleaned_data and form.cleaned_data['is_published'] == 'on':
            form.instance.published_date = timezone.now()
        form.save() 

        return super(CourseCreate, self).form_valid(form)

    def get_form_kwargs(self):
        kw = super(CourseCreate, self).get_form_kwargs()
        kw['request'] = self.request
        kw['kw'] = self.kwargs
        return kw


class CourseUpdate(UpdateView):
    template_name = 'tasks/course_form.html'
    form_class = CourseForm
    model = Course

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().owner != request.user:
            return redirect('tasks:view_course', pk=kwargs['pk'])
        return super(CourseUpdate, self).dispatch(request, *args, **kwargs)


    def form_valid(self, form):
        if 'is_published' in form.cleaned_data and form.cleaned_data['is_published'] == 'on':
            form.instance.published_date = timezone.now()
        form.save() 
        return super(CourseUpdate, self).form_valid(form)

    def get_form_kwargs(self):
        kw = super(CourseUpdate, self).get_form_kwargs()
        kw['request'] = self.request
        kw['kw'] = self.kwargs
        return kw


class CourseDetail(DetailView):
    model = Course
    template_name = 'tasks/course_detail.html'
    context_object_name = 'course'

    def dispatch(self, request, *args, **kwargs):
        if not self.get_object().is_published and self.get_object().owner != request.user:
            return redirect('tasks:course_list')
        return super(CourseDetail, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['subscribes'] = Course.objects.filter(subscribes__owner=self.request.user)

        return context


class CourseList(ListView):
    model = Course
    context_object_name = 'courses'
    template_name = 'tasks/course_list.html'

    def get_queryset(self):
        if self.request.user.is_teacher:
            return Course.objects.filter(owner=self.request.user)
        else:
             # Subscribes.objects.filter(owner=self.request.user)
            return Course.objects.filter(subscribes__owner=self.request.user, is_published=True)
    

class TaskCreate(CreateView):
    template_name = 'tasks/task_form.html'
    form_class = TaskForm
    model = Task


    def get_success_url(self, **kwargs):         
        return reverse_lazy("tasks:view_task", kwargs={'pk': kwargs['pk'], 'course_id':kwargs['course_id']})
        

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_teacher:
            return redirect('tasks:task_list', course_id=kwargs['course_id'])

        course = get_object_or_404(Course, pk=kwargs['course_id'])
        
        if course.owner != request.user:
            return redirect('tasks:task_list', course_id=kwargs['course_id'])

        return super(TaskCreate, self).dispatch(request, *args, **kwargs)


    def form_valid(self, form):
        form.instance.owner = self.request.user

        course = get_object_or_404(Course, pk=self.kwargs['course_id'])
        form.instance.course = course

        if 'is_published' in form.cleaned_data and form.cleaned_data['is_published'] == 'on':
            form.instance.published_date = timezone.now()
        task = form.save() 

        return HttpResponseRedirect(self.get_success_url(pk=task.pk, course_id=course.pk))

    def get_form_kwargs(self):
        kw = super(TaskCreate, self).get_form_kwargs()
        kw['request'] = self.request
        kw['kw'] = self.kwargs
        return kw

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = get_object_or_404(Course, pk=self.kwargs['course_id'])

        return context


class TaskUpdate(UpdateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskForm

    def get_success_url(self, **kwargs):         
        return reverse_lazy("tasks:view_task", kwargs={'pk': self.get_object().pk, 'course_id':kwargs['course_id']})


    def dispatch(self, request, *args, **kwargs):
        if self.get_object().owner != request.user:
            return redirect('tasks:view_task', pk=kwargs['pk'], course_id=kwargs['course_id'])
        return super(TaskUpdate, self).dispatch(request, *args, **kwargs)


    def form_valid(self, form):
        task = form.save() 
        return HttpResponseRedirect(self.get_success_url(pk=task.pk, course_id=task.course.pk))


    def get_form_kwargs(self):
        kw = super(TaskUpdate, self).get_form_kwargs()
        kw['request'] = self.request
        kw['kw'] = self.kwargs
        return kw


class TaskDetail(DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
    context_object_name = 'task'

    def dispatch(self, request, *args, **kwargs):
        if not self.get_object().is_published and self.get_object().owner != request.user:
            return redirect('tasks:view_task', pk=kwargs['pk'], course_id=kwargs['course_id'])

        if request.user.is_teacher:
            self.template_name = 'tasks/task_detail_teacher.html'

        return super(TaskDetail, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = get_object_or_404(Course, pk=self.kwargs['course_id'])        
        context['tasks'] = Task.objects.filter(course=course)
        if self.request.user.is_teacher:
            return context
        course = get_object_or_404(Course, pk=self.kwargs['course_id'])
        context['progress'] = Progress.objects.filter(owner=self.request.user, course=course)
        context['tasks'] = Task.objects.filter(course=course).annotate(is_passed=F('progress__is_passed'))
        context['doneTasks'] = Progress.objects.filter(owner=self.request.user, course=course, is_passed=True)
        progress = Progress.objects.filter(owner=self.request.user, course=course, task=self.get_object())
        if progress.first():
            context['data'] = progress.first().data
        return context


class TaskList(ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/task_list.html'

    def get_queryset(self):
        course = get_object_or_404(Course, pk=self.kwargs['course_id'])
        if self.request.user == course.owner:
            return Task.objects.filter(owner=self.request.user, course=course)
        else:
            return Task.objects.filter(owner=self.request.user, course=course, is_published=True)   

        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = get_object_or_404(Course, pk=self.kwargs['course_id'])
        context['course'] = course
        return context


class Subscribe(View):

    def dispatch(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs['pk'])
        res = 'FAIL'
        if not request.user.is_teacher and course.is_published:
            progress, created = Subscribes.objects.get_or_create(owner=request.user, course=course)
            if created:
                res = 'OK'
        return JsonResponse({'result': res}) 


class Unsubscribe(View):

    def dispatch(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs['pk'])
        res = 'FAIL'
        if not request.user.is_teacher and course.is_published:
            progress = get_object_or_404(Subscribes, owner=request.user, course=course)
            if progress != None:
                progress.delete()
                res = 'OK'
        return JsonResponse({'result': res}) 


class GlobalCourseList(ListView):
    model = Course
    context_object_name = 'courses'
    template_name = 'tasks/global_course_list.html'

    def get_queryset(self):
        return Course.objects.filter(is_published=True)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subscribes'] = Course.objects.filter(subscribes__owner=self.request.user)
        return context


class ToggleLike(View):
    def dispatch(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs['pk'])
        res = 'FAIL'
        if course.is_published:
            like, created = Like.objects.get_or_create(owner=request.user, course=course)
            if created:
                like.delete()
                res = 'DELETED'
            else:
                like.save()
                res = 'LIKED'

        return JsonResponse({'result': res})  


class DatabaseCreate(CreateView):
    template_name = "tasks/db_form.html"
    form_class = DataBaseForm
    model = Task_db


    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_teacher:
            return redirect('tasks:course_list')

src/templates/tasks/course_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} 
       Курс "{{course.name}}"
{% endblock %}

{% block extra_links %}
    <script src="{% static 'base/subscribe.js' %}"></script>
{% endblock %}

{% block form %} 
    <a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a>
    <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a>  
    <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
{% endblock %}


{% block content %}
	<div class="row">
		<div class="col-md-8 col-sm-12">
			<h1>{{course.name|capfirst}}</h1>
			<br>
			{% if user == course.owner%}
			<a href="{% url 'tasks:task_list' course_id=course.pk %}" class="btn btn-secondary">Упражнения</a>
			<a href="{% url 'tasks:update_course' pk=course.pk %}" class="btn btn-secondary">Редактировать</a>
			<a href="#" class="btn btn-secondary">Статистика</a>
			<a href="{% url 'tasks:invite_students' course_id=course.pk %}" class="btn btn-secondary">Пригласить студентов</a>
			{% else %}
			<!-- этот span критически важен!!!! -->
			<span>  
			{% if course in subscribes %}
			<a href="{% url 'tasks:course_unsubscribe' pk=course.pk %}" class="btn btn-danger btn-lg" onclick="unsubscribe(event)">Отписаться</a>
			{% else %}
			<a href="{% url 'tasks:course_subscribe' pk=course.pk %}" class="btn btn-primary btn-lg" onclick="subscribe(event, '', 'Отписаться')">Записаться на курс</a>
			{% endif %}
			</span>
			<!-- этот span заканчивается тут!!!! -->
			<a href="{% url 'tasks:task_list' course_id=course.pk %}" class="btn btn-link btn-lg">Упражнения</a>
			{% endif %}
		</div>
		<div class="col-md-4 col-sm-12">
			<img src="https://s31333.cdn.ngenix.net/f1367c/CACHE/images/cover/654f3a08fd4e191200fd890c4772620e4fa36630/53eae97be9910368bafbff6771ab81d0.png" alt="" class="course-image mx-auto" style="display: block;">
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-8">
		{{course.description|linebreaks}}
		</div>
		<div class="col-4">
			<table class="table table-sm noborder">
	  <tbody>
	    <tr>
	      <th scope="row">Автор</th>
	      <td>{{course.owner.get_full_name}}</td>
	    </tr>
	    <tr>
	      <th scope="row">Количество заданий</th>
	      <td>{{course.tasks.count}}</td>
	    </tr>
	    <tr>
	      <th scope="row">Сложность</th>
	      <td>
	      	{% with ''|center:course.difficulty as range %}
				{% for _ in range %}
				    <i class="fas fa-star"></i>
				{% endfor %}
			{% endwith %}

			{% with course.difficulty|add:':' as len %}
				{% with '12345'|slice:len as range %}
						{% for _ in range %}
						    <i class="far fa-star"></i>
						{% endfor %}
				{% endwith %}
			{% endwith %}	
	      </td>
	    </tr>
	    <tr>
	      <th scope="row">Дата публикации</th>
	      <td>{{course.published_date|date:'d.m.Y'|default:"Не опубликован"}}</td>
	    </tr>
	  </tbody>
	</table>
		</div>


		<!-- <div class="btn-group" role="group">

	    {% if user.is_teacher %}
	      <a href="{% url 'tasks:update_course' pk=course.pk %}" class="btn btn-secondary">Редактировать</a> 
	      
		  <div class="btn-group" role="group">
		    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		      Дополнительно
		    </button>
		    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                    <a href="{% url 'tasks:task_list' course_id=course.id %}" class="dropdown-item"">Список заданий</a>
                    <a href="#" class="dropdown-item">Статистика</a>
                    <a href="#" class="dropdown-item">Пригласить студентов</a>
		    </div>
		  </div>
		{% else %}
            <a href="#" class="btn btn-success">Записаться на курс</a>
            <a href="#" class="btn btn-danger">Отписаться от курса</a>
        {% endif %}
		</div> -->

	</div>
{% endblock %}

src/templates/tasks/course_form.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block title %} 
       Создание курса
{% endblock %}


{% block form %} 
    <a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a> 
    <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a>  
    <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
{% endblock %}


{% block content %}
	{% if form.instance.pk %}
	<h3>Редактирование курса "{{form.instance.name}}"</h3>
	<br>
	<form action="{% url 'tasks:update_course' pk=form.instance.pk %}" method='POST'>
	{% else %}
	<h2>Создать новый курс</h2>
	<br>
	<form action="{% url 'tasks:create_course' %}" method='POST'>
	{% endif%}

		{% csrf_token %}

        {% for field in form %}

        {% if field.name == 'is_published' %}

		<div class="form-group row">
            <label class="col-sm-2">{{ field.label }}</label>
            <div class="col-sm-10">
				<div class="form-check">
			          <label class="form-check-label">
			          {{ field |add_class:"form-check-input" }}
		   	          </label>
		        </div>
	        </div>  
        </div>

        {% else %}

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field |add_class:"form-control" }}
            </div>  
        </div>

        {% endif %}


  


        {% if field.errors %}
            {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
              {{error}}
            </div>
            {% endfor %}
        {% endif %}
 
        
        {% endfor %}

	    <button class="btn btn-lg btn-primary btn-block" type="submit">Сохранить</button>

   </form>
{% endblock %}

src/templates/tasks/course_list.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Ваши курсы {% endblock %} 

{% block extra_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/course_list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'base/icons.css' %}">
{% endblock %} 

{% block form %} 
<a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a> <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a> <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a> 
{% endblock %} 

{% block content %}

<div class="d-flex justify-content-between align-items-center">
    <h4 class="mb-0 align-middle">Ваши курсы</h4>
    {% if user.is_teacher %}
    <a class="btn btn-primary" href="{% url 'tasks:create_course' %}">Новый курс</a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'tasks:global_course_list' %}">Найти курсы</a>
    {% endif %}
</div>
<br>


<div class="row courses-list">
    {% for course in courses %}

    <div class="col-md-4 col-sm-6 col-xs-12 col b_course_container">
        <div class="course">
            <a href="{% url 'tasks:view_course' pk=course.pk %}" class="uho">
          
            
                <img src="https://s31333.cdn.ngenix.net/f1367c/CACHE/images/cover/654f3a08fd4e191200fd890c4772620e4fa36630/53eae97be9910368bafbff6771ab81d0.png" alt="" class="course-image">
          
            </a>

            <div class="course-content">

            <div class="course-title"><a href="{% url 'tasks:view_course' pk=course.pk %}">{{course.name|capfirst}}</a></div>

            <div class="progress"></div>

            <div class="course-info">
            <div class="d-flex justify-content-between align-items-center">
                <span>Cложность:</span>
                <span> {% with ''|center:course.difficulty as range %} {% for _ in range %} <i class="fas fa-star"></i> {% endfor %} {% endwith %} {% with course.difficulty|add:':' as len %} {% with '12345'|slice:len as range %} {% for _ in range %} <i class="far fa-star"></i> {% endfor %} {% endwith %} {% endwith %}</span>
            </div>
            </div>
            <div class="progress"></div>

            <div class="course-info">
            <div class="d-flex justify-content-between align-items-center">
                <span>Cтатус:</span>
                <span> {% if course.is_published %} Опубликован {% else %} Скрыт {% endif %}</span>
            </div>
            </div>

            <div class="progress"></div>

            <div class="course-info">
            <div class="d-flex justify-content-between align-items-center">
                <span>Рейтинг:</span>
                <span>{{course.rating}}</span>
            </div>
            </div>
            
<!--                 <button aria-expanded="false" aria-haspopup="true" class="btn btn-secondary" data-toggle="dropdown" id="dropdownMenu{{forloop.counter}}" type="button"><i class="fas fa-bars"></i></button> -->

<!--                 <div aria-labelledby="dropdownMenu{{forloop.counter}}" class="dropdown-menu dropdown-menu-right">
	                <a href="{% url 'tasks:task_list' course_id=course.pk %}" class="dropdown-item">Список заданий</a>
	                {% if user.is_teacher %}
                    <a href="{% url 'tasks:update_course' pk=course.pk %}" class="dropdown-item">Редактировать</a> 
                    <a href="#" class="dropdown-item">Статистика</a>
                    <a href="#" class="dropdown-item">Пригласить студентов</a>
                    {% else %}
                    <a href="#" class="dropdown-item">Записаться на курс</a>
                    <a href="#" class="dropdown-item">Отписаться от курса</a>
                    {% endif %}
                </div> -->
            </div>


            <div class="footer-line">
                <a href="{% url 'tasks:update_course' pk=course.pk %}">Редактировать</a>
            </div>
       


        
        </div>
    </div>
    {% empty %}

    <p style="padding-left: 10px;">Пока нет курсов</p>
    {% endfor %}
</div>
{% endblock %}

src/templates/tasks/db_form.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block title %} 
       Новая база данных
{% endblock %}


{% block form %} 
    <a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a> 
    <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a>  
    <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
{% endblock %}


{% block content %}
	<h2>Новая база данных</h2>
	<br>
	<form method="post">
		{% csrf_token %}
        {% for field in form %}
         <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field |add_class:"form-control" }}
            </div>  
        </div>

        {% if field.errors %}
            {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
              {{error}}
            </div>
            {% endfor %}
        {% endif %}

        {% endfor %}
        
		<button class="btn btn-lg btn-primary btn-block" type="submit">Создать</button>

	</form>
	
{% endblock %}

src/templates/tasks/global_course_list.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Список курсов {% endblock %} 

{% block extra_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/course_list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'base/icons.css' %}">
    <script src="{% static 'base/subscribe.js' %}"></script>
{% endblock %} 

{% block form %} 
<a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a> <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a> <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a> 
{% endblock %} 

{% block content %}

<div class="d-flex justify-content-between align-items-center">
    <h4 class="mb-0 align-middle">Все курсы</h4>
    {% if user.is_teacher %}
    <a class="btn btn-primary" href="{% url 'tasks:create_course' %}">Новый курс</a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'tasks:global_course_list' %}">Найти курсы</a>
    {% endif %}
</div>
<br>


<div class="row courses-list">
    {% for course in courses %}

    <div class="col-md-4 col-sm-6 col-xs-12 col b_course_container">
        <div class="course">
            <a href="{% url 'tasks:view_course' pk=course.pk %}" class="uho">
          
            
                <img src="https://s31333.cdn.ngenix.net/f1367c/CACHE/images/cover/654f3a08fd4e191200fd890c4772620e4fa36630/53eae97be9910368bafbff6771ab81d0.png" alt="" class="course-image">
          
            </a>

            <div class="course-content">

            <div class="course-title"><a href="{% url 'tasks:view_course' pk=course.pk %}">{{course.name|capfirst}}</a></div>

            <div class="progress"></div>

            <div class="course-info">
            <div class="d-flex justify-content-between align-items-center">
                <span>Cложность:</span>
                <span> {% with ''|center:course.difficulty as range %} {% for _ in range %} <i class="fas fa-star"></i> {% endfor %} {% endwith %} {% with course.difficulty|add:':' as len %} {% with '12345'|slice:len as range %} {% for _ in range %} <i class="far fa-star"></i> {% endfor %} {% endwith %} {% endwith %}</span>
            </div>
            </div>
            <div class="progress"></div>

            <div class="course-info">
            <div class="d-flex justify-content-between align-items-center">
                <span>Cтатус:</span>
                <span> {% if course.is_published %} Опубликован {% else %} Скрыт {% endif %}</span>
            </div>
            </div>

            <div class="progress"></div>

            <div class="course-info">
            <div class="d-flex justify-content-between align-items-center">
                <span>Рейтинг:</span>
                <span>{{course.rating}}</span>
            </div>
            </div>

            </div>

            {% if user == course.owner or not user.is_teacher %}
            <div class="footer-line">
            {% if user == course.owner %}
                <a href="{% url 'tasks:update_course' pk=course.pk %}">Редактировать</a>
            {% else %}
                {% if course in subscribes %}
                <span>Вы подписаны</span>
                {% else %}
                <a href="{% url 'tasks:course_subscribe' pk=course.pk %}" onclick="subscribe(event)">Подписаться</a>
                {% endif %}
            {% endif %}
            </div>
            {% endif %}
       


        
        </div>
    </div>
    {% empty %}

    <p style="padding-left: 10px;">Пока нет курсов</p>
    {% endfor %}
</div>
{% endblock %}