src/accounts/urls.py
from django.urls import path, re_path

from django.contrib.auth import views as auth_views
from .views import UserCreateView, UserUpdateView, activate, UserDetailView, thanks
from .views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView, LoginView, LogoutView

from django.urls import reverse_lazy

app_name = 'accounts'


urlpatterns = [

    path('register/', UserCreateView.as_view(), name='register'),
    path('thanks/', thanks, name='thanks'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    path('edit/', UserUpdateView.as_view(), name="edit"),
    path('', UserDetailView.as_view(), name="profile" ),

    re_path(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', PasswordResetCompleteView.as_view(), name='password_reset_complete', ),
    re_path(r'^password_change/$', PasswordChangeView.as_view(), name="password_change"),
    re_path(r'^password_change/done/$', PasswordChangeDoneView.as_view(), name="password_change_done"),

]

src/tasks/urls.py
from django.urls import path, re_path
from .views import CourseList, CourseCreate, CourseDetail, CourseUpdate, GlobalCourseList
from .views import TaskList, TaskCreate, TaskDetail, TaskUpdate
from .views import Subscribe, Unsubscribe, ToggleLike
from .views import TableCreate, DatabaseCreate
from .views import TestMysql, DatabaseDetail, TableDetail, UpdateProgress

from einvite.views import invites

app_name = 'tasks'


urlpatterns = [

    path('all/', GlobalCourseList.as_view(), name='global_course_list'),

    path('', CourseList.as_view(), name='course_list'),
    path('new/', CourseCreate.as_view(), name='create_course'),
    path('<int:pk>/', CourseDetail.as_view(), name='view_course'),
    path('<int:pk>/like', ToggleLike.as_view(), name='like_course'),
    path('<int:pk>/edit/', CourseUpdate.as_view(), name='update_course'),

    path('<int:course_id>/tasks/', TaskList.as_view(), name='task_list'),
    path('<int:course_id>/tasks/new/', TaskCreate.as_view(), name='create_task'),
    path('<int:course_id>/tasks/<int:pk>/', TaskDetail.as_view(), name='view_task'),
    path('<int:course_id>/tasks/<int:pk>/progress', UpdateProgress.as_view(), name='update_progress'),
    path('<int:course_id>/tasks/<int:pk>/edit/', TaskUpdate.as_view(), name='update_task'),

    path('<int:course_id>/invite/', invites, name='invite_students'),

    path('<int:pk>/subscribe/', Subscribe.as_view(), name="course_subscribe"),
    path('<int:pk>/unsubscribe/', Unsubscribe.as_view(), name="course_unsubscribe"),

    path('db/new/', DatabaseCreate.as_view(), name="create_db"),
    path('db/<int:pk>', DatabaseDetail.as_view(), name="view_task_db"),
    path('table/new/', TableCreate.as_view(), name="create_table"),
    path('table/<int:pk>', TableDetail.as_view(), name="view_task_table"),

    path('test/', TestMysql.as_view()),



]

src/templates/acc_active_email.html
{% autoescape off %}
Здравстуйте, {{user.first_name}}!

Спасибо что зарегистрировались на нашем сайте. Пожалуйста, перейдите по ссылке, чтобы подтвердить электронную почту.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
Если ссылка неактивна, скопируйте ее в адресную строку Вашего браузера и нажмите Enter.

С уважением, 
Команда PineappleSQL
{% endautoescape %}

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href='{%static "base/style.css"%}'>
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
  
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  

   <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    
  {% block extra_links %}
  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-toggleable navbar-light bg-faded">
    <div class="container">
      <div class="collapse navbar-collapse">
        <a class="navbar-brand" href="#">Pineapple SQL</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{%  url 'tasks:course_list' %}">Курсы</a>
          </li>
        </ul>
        {% block form %}{% endblock %}
      </div>
    </div>
  </nav>
  <div class="container" id="main">
    {% block content %}{% endblock %}
  </div>
  {% block footer %}{% endblock %}
</body>
</html>

src/templates/invite_email.html
{% autoescape off %}
Здравстуйте!

{{user.get_short_name}} приглашает вас записаться на курс {{course.name}}

Для прохождения курса, зарегистрируйтесь на сайте: 
http://{{ domain }}

Ссылка на курс
http://{{ domain }}{% url 'tasks:view_course' pk=course.pk %}

Если ссылка неактивна, скопируйте ее в адресную строку Вашего браузера и нажмите Enter.

С уважением, 
Команда PineappleSQL
{% endautoescape %}