src/accounts/urls.py
from django.urls import path, re_path

from django.contrib.auth import views as auth_views
from .views import UserCreateView, UserUpdateView, activate, UserDetailView, thanks
from .views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView, LoginView, LogoutView

from django.urls import reverse_lazy

app_name = 'accounts'


urlpatterns = [

    path('register/', UserCreateView.as_view(), name='register'),
    path('thanks/', thanks, name='thanks'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    path('edit/', UserUpdateView.as_view(), name="edit"),
    path('', UserDetailView.as_view(), name="profile" ),

    re_path(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', PasswordResetCompleteView.as_view(), name='password_reset_complete', ),
    re_path(r'^password_change/$', PasswordChangeView.as_view(), name="password_change"),
    re_path(r'^password_change/done/$', PasswordChangeDoneView.as_view(), name="password_change_done"),

]

src/tasks/urls.py
from django.urls import path, re_path
from .views import CourseList, CourseCreate, CourseDetail, CourseUpdate, GlobalCourseList
from .views import TaskList, TaskCreate, TaskDetail, TaskUpdate
from .views import Subscribe, Unsubscribe, ToggleLike
from .views import TableCreate, DatabaseCreate
from .views import TestMysql, DatabaseDetail, TableDetail, UpdateProgress

from einvite.views import invites

app_name = 'tasks'


urlpatterns = [

    path('all/', GlobalCourseList.as_view(), name='global_course_list'),

    path('', CourseList.as_view(), name='course_list'),
    path('new/', CourseCreate.as_view(), name='create_course'),
    path('<int:pk>/', CourseDetail.as_view(), name='view_course'),
    path('<int:pk>/like', ToggleLike.as_view(), name='like_course'),
    path('<int:pk>/edit/', CourseUpdate.as_view(), name='update_course'),

    path('<int:course_id>/tasks/', TaskList.as_view(), name='task_list'),
    path('<int:course_id>/tasks/new/', TaskCreate.as_view(), name='create_task'),
    path('<int:course_id>/tasks/<int:pk>/', TaskDetail.as_view(), name='view_task'),
    path('<int:course_id>/tasks/<int:pk>/progress', UpdateProgress.as_view(), name='update_progress'),
    path('<int:course_id>/tasks/<int:pk>/edit/', TaskUpdate.as_view(), name='update_task'),

    path('<int:course_id>/invite/', invites, name='invite_students'),

    path('<int:pk>/subscribe/', Subscribe.as_view(), name="course_subscribe"),
    path('<int:pk>/unsubscribe/', Unsubscribe.as_view(), name="course_unsubscribe"),

    path('db/new/', DatabaseCreate.as_view(), name="create_db"),
    path('db/<int:pk>', DatabaseDetail.as_view(), name="view_task_db"),
    path('table/new/', TableCreate.as_view(), name="create_table"),
    path('table/<int:pk>', TableDetail.as_view(), name="view_task_table"),

    path('test/', TestMysql.as_view()),



]

src/templates/invite/invite_students.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %} 
       Пригласить студентов
{% endblock %}

{% block extra_links %}
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
	<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
	<link rel="stylesheet" href="style.css">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

		<script type="text/javascript">
		
		var link_list = [];

		// $("#emaillist").keypress(function() {
		// 	find_email();
		// });

		function before_submit() {
			$('#emaillist').val("");
			link_list.forEach((item)=> {
				var text = $('#emaillist').val();
				text += " " + item; 
				$('#emaillist').val(text);
			})
			// alert($('#emaillist').val());
		}

		function delete_email(ob) {						
			link_list.splice(link_list.indexOf(ob.html()), 1);
			ob.remove();
		}

		function find_email() {
			var list = $('#emaillist').val();
			var exp = /[\S]+@[\S]+\.[\S]+/ig;

			var raw_links = list.match(exp);			
			if (raw_links != null){
				raw_links.forEach((item)=>{
					let e_item = document.createElement("li");
					e_item.setAttribute('class', 'list-group-item')
					e_item.setAttribute('onclick',"delete_email($(this))");
			        e_item.append(item);
			        list = list.replace(item, '');
					$(".list-group-flush").append(e_item);					
					link_list[link_list.length] = item;
			    });
				$("#emaillist").val(list);
			}			
		}

	</script>
{% endblock %}

{% block form %} 
    <a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a>
    <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a>  
    <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
{% endblock %}

{% block content %}
		<h3>Пригласить студентов в курс {{ course }}</h3>
		<div class="row card-test">			
			<div class="col-sm-4 card-outline ">
				<h5>Выбранные адреса</h5>				
				<div class="text-muted">
					<small>Нажмите на адрес, чтобы удалить его</small>
				</div>											
				<ul class="list-group list-group-flush"></ul>					
			</div>
			<div class="col-sm-8 card-outline ">
				<h5>Введите адреса</h5>
				<form method="post" accept-charset="utf-8">
					{% csrf_token %}
					{% for field in form %}
						{{ field |add_class:"form-control" }}
					{% if field.errors %}
			            {% for error in field.errors %}
			            <div class="alert alert-danger" role="alert">
			              {{error}}
			            </div>
			            {% endfor %}
			        {% endif %}
					{% endfor %}
					<br>
					<div id="add" onclick="find_email()" class="btn btn-secondary">Добавить адреса</div>
					<input onclick="before_submit()" class="btn btn-primary" type="submit" name="submit">
				</form>
			</div>
		</div>
{% endblock %}

src/templates/invite/thanks.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %} 
       Курс "{{course.name}}"
{% endblock %}

{% block extra_links %}
    <script src="{% static 'base/subscribe.js' %}"></script>
{% endblock %}

{% block form %} 
    <a class="nav-link" href="{% url 'accounts:profile' %}">{{user.get_short_name}}</a>
    <a class="nav-link" href="{% url 'accounts:edit' %}">Настройки</a>  
    <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
{% endblock %}


{% block content %}
        <h2>{{header}}</h2>
        <br>
	<a href="{% url 'tasks:view_course' pk=pk %}">{{a|safe}}</a>

{% endblock %}